{% set name = "cosmopy" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cosmopy-{{ version }}.tar.gz
  sha256: 081a1932a1dca799c70343a7e607e91b476811f90a79246081a1b7ef3778b49b

build:
  entry_points:
    - cosmo = cosmopy.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - setuptools >=40.6.0
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - astropy-base
    - future
    - click

test:
  imports:
    - cosmopy
  commands:
    - pip check
    - cosmo --help
  requires:
    - pip

about:
  home: https://github.com/lzkelley/cosmopy
  summary: 'Quickly calculate cosmological parameters.'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davecwright3
